package entity;
// Generated Jul 23, 2019 11:52:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name="city"
    ,catalog="museums"
)
public class City  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Museum> museums = new HashSet<Museum>(0);

    public City() {
    }

    public City(String name, Set<Museum> museums) {
       this.name = name;
       this.museums = museums;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<Museum> getMuseums() {
        return this.museums;
    }
    
    public void setMuseums(Set<Museum> museums) {
        this.museums = museums;
    }




}


