package entity;
// Generated Jul 23, 2019 11:52:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Museum generated by hbm2java
 */
@Entity
@Table(name="museum"
    ,catalog="museums"
)
public class Museum  implements java.io.Serializable {


     private Integer id;
     private City city;
     private Museumtpye museumtpye;
     private String name;
     private String address;
     private String imageurl;

    public Museum() {
    }

    public Museum(City city, Museumtpye museumtpye, String name, String address, String imageurl) {
       this.city = city;
       this.museumtpye = museumtpye;
       this.name = name;
       this.address = address;
       this.imageurl = imageurl;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cityid", nullable=false)
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="typeid", nullable=false)
    public Museumtpye getMuseumtpye() {
        return this.museumtpye;
    }
    
    public void setMuseumtpye(Museumtpye museumtpye) {
        this.museumtpye = museumtpye;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="address", nullable=false, length=250)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="imageurl", nullable=false, length=500)
    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }




}


