package entity;
// Generated Jul 23, 2019 11:52:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="museums"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String surname;
     private String pssword;
     private String email;

    public User() {
    }

    public User(String name, String surname, String pssword, String email) {
       this.name = name;
       this.surname = surname;
       this.pssword = pssword;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", nullable=false, length=45)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="pssword", nullable=false, length=45)
    public String getPssword() {
        return this.pssword;
    }
    
    public void setPssword(String pssword) {
        this.pssword = pssword;
    }
    
    @Column(name="email", nullable=true, length=250)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
}


